apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: stable
controlPlaneEndpoint: "{{ VIPMasterNode }}:{{ PortAPI }}"
etcd:
    external:
        endpoints:
        - https://192.168.141.230:{{ Portetcd }}
        - https://192.168.141.238:{{ Portetcd }}
        - https://192.168.141.239:{{ Portetcd }}
        caFile: /etc/kubernetes/pki/etcd/ca.crt
        certFile: /etc/kubernetes/pki/apiserver-etcd-client.crt
        keyFile: /etc/kubernetes/pki/apiserver-etcd-client.key
networking:
  podSubnet: 10.244.0.0/16
          